import type { ResearchDataset } from '@thunderdome/research-core';
import {
  closeResearchStore,
  createResearchStore,
  getResearchDataset,
} from '@thunderdome/research-store';

/** This domain's `dataset_id` in the shared research store — see
 * `research-store/src/migrations/0003_quantum_seed.ts` (generated by
 * `scripts/generateQuantumSeedMigration.ts`) for where this id's content actually lives. */
export const QUANTUM_DATASET_ID = 'dataset-quantum-skeleton';

/**
 * Deliberately a skeleton, not a domain model: just enough to prove that
 * `@thunderdome/research-core`'s schema is generic across a SECOND, unrelated domain — using its
 * own vocabulary (`"quantum-architecture"`, `"error-correction-code"`, ...) that research-core
 * never inspects — without requiring any change to research-core itself (spec §53). Building out
 * this package's real quantum research is future work; see README.md.
 */
export const QUANTUM_FIXTURE_IDS = {
  entities: {
    ibmQuantum: 'entity-ibm-quantum',
    superconductingQubit: 'entity-superconducting-qubit',
    surfaceCode: 'entity-surface-code',
  },
  relationships: {
    ibmQuantumUsesSuperconductingQubit: 'rel-ibm-quantum-uses-superconducting-qubit',
  },
  evidence: {
    ibmSurfaceCodeResults: 'evidence-ibm-surface-code-results',
  },
  hypotheses: {
    surfaceCodeNecessary: 'hypothesis-surface-code-necessary',
  },
} as const;

/**
 * Loads the quantum skeleton dataset by replaying `@thunderdome/research-store`'s migrations into
 * a fresh in-memory database — instead of constructing it inline, as this function used to (see
 * `scripts/generateQuantumSeedMigration.ts` for how that inline construction was captured as the
 * seed migration). Mirrors `@thunderdome/research-fusion`'s `createFusionFixtureDataset()`.
 */
export function createQuantumSkeletonDataset(): ResearchDataset {
  const store = createResearchStore(':memory:');
  try {
    const result = getResearchDataset(store, QUANTUM_DATASET_ID);
    if (!result.ok) {
      throw new Error(
        `quantum research dataset "${QUANTUM_DATASET_ID}" failed to load: ${result.reason}`,
      );
    }
    return result.value;
  } finally {
    closeResearchStore(store);
  }
}
