/**
 * Turns a JSON "research update" file into a NEW, auto-numbered migration file under
 * `@thunderdome/research-store`'s `src/migrations/` — the no-coding-agent path for growing the
 * fusion research dataset, now that `data/dataset.json` has been retired (see
 * `docs/adr/0014-sqlite-standard-and-migrations.md`). An update file is a PARTIAL
 * `ResearchDataset` (`ResearchUpdate` — see `@thunderdome/research-store`): any subset of
 * `entities`/`relationships`/.../`questions`, each an array of full research-core objects using
 * EXISTING entity ids (see `scripts/printKnownEntities.ts`) or freshly minted ones following this
 * dataset's own `entity-<slug>`/`rel-<slug>`/`evidence-<slug>` convention (see
 * `FUSION_FIXTURE_IDS` in `../src/fixture.ts`).
 *
 * Merge semantics are `@thunderdome/research-store`'s `mergeResearchUpdate` (ported there from
 * this script's original JSON-file-rewriting version — see that module for the full rules: a new
 * id in any collection is appended, an id collision is refused except a relationship gaining new
 * `states[]`). The WHOLE merged dataset is validated before anything is written; any issue refuses
 * the whole batch, and no file is written — the same refuse-rather-than-guess posture
 * `packages/stock-market-4/market-data/scripts/fetchAndAppendBars.ts` already uses.
 *
 * Usage:
 *   yarn workspace @thunderdome/research-fusion run apply:research-update -- \
 *     --update-file /path/to/update.json
 *
 * The generated migration file still needs ONE manual step: add its import + array entry to
 * `research-store/src/migrations/index.ts` (this script prints the exact lines) — kept manual
 * rather than auto-edited, since a hand-maintained migrations list is simpler and more reviewable
 * than a second file a script silently rewrites.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  createResearchStore,
  getResearchDataset,
  renderUpdateSql,
  type MergeSummary,
  type ResearchStore,
  type ResearchUpdate,
} from '@thunderdome/research-store';
import { nextMigrationNumber, renderMigrationFileSource } from '@thunderdome/sqlite-migrations';
import { FUSION_DATASET_ID } from '../src/fixture.js';

export {
  bumpDatasetVersion,
  mergeResearchUpdate,
  type ResearchUpdate,
} from '@thunderdome/research-store';

const __dirname = dirname(fileURLToPath(import.meta.url));
const DEFAULT_MIGRATIONS_DIR = resolve(__dirname, '../../store/src/migrations');

export interface ApplyResearchUpdateOptions {
  /** Defaults to a fresh in-memory store built from `@thunderdome/research-store`'s own compiled
   * migrations — i.e. the real, current fusion dataset. Tests pass their own pre-seeded store. */
  store?: ResearchStore;
  datasetId?: string;
  migrationsDir?: string;
  now?: string;
}

export type ApplyResult =
  | {
      ok: true;
      migrationId: string;
      migrationPath: string;
      migrationFileName: string;
      exportName: string;
      newVersion: string;
      summary: MergeSummary;
    }
  | { ok: false; reason: string };

/**
 * The full load -> merge -> validate -> generate pipeline, factored out from `main()` with
 * options so it's testable end-to-end (including the "nothing is written on refusal" guarantee)
 * against a temp store/migrations directory rather than the real ones.
 */
export function applyResearchUpdateToMigration(
  updateFilePath: string,
  options: ApplyResearchUpdateOptions = {},
): ApplyResult {
  const datasetId = options.datasetId ?? FUSION_DATASET_ID;
  const migrationsDir = options.migrationsDir ?? DEFAULT_MIGRATIONS_DIR;
  const now = options.now ?? new Date().toISOString();
  const store = options.store ?? createResearchStore(':memory:');

  let update: ResearchUpdate;
  try {
    update = JSON.parse(readFileSync(resolve(updateFilePath), 'utf8')) as ResearchUpdate;
  } catch (error) {
    return {
      ok: false,
      reason: `Could not read/parse "${updateFilePath}": ${error instanceof Error ? error.message : String(error)}`,
    };
  }

  const currentResult = getResearchDataset(store, datasetId);
  if (!currentResult.ok) {
    return { ok: false, reason: currentResult.reason };
  }

  const rendered = renderUpdateSql(currentResult.value, update, now);
  if (!rendered.ok) {
    return { ok: false, reason: rendered.reason };
  }

  const nextNumber = nextMigrationNumber(migrationsDir);
  const migrationId = `research-store/${nextNumber}_fusion_update`;
  const exportName = `migration${nextNumber}FusionUpdate`;
  const migrationFileName = `${nextNumber}_fusion_update.ts`;
  const migrationPath = join(migrationsDir, migrationFileName);

  const source = renderMigrationFileSource({
    exportName,
    id: migrationId,
    sql: rendered.value.sql,
    docComment: `/** A research update to the "${datasetId}" dataset (version -> "${rendered.value.newVersion}"), generated by\n * \`research/fusion/scripts/applyResearchUpdate.ts\` from an update file — never hand-edit this\n * file; a correction is always a NEW migration. */`,
  });
  writeFileSync(migrationPath, source, 'utf8');

  return {
    ok: true,
    migrationId,
    migrationPath,
    migrationFileName,
    exportName,
    newVersion: rendered.value.newVersion,
    summary: rendered.value.summary,
  };
}

function parseArgs(argv: string[]): Record<string, string> {
  const args: Record<string, string> = {};
  for (let i = 0; i < argv.length; i++) {
    const token = argv[i];
    if (token?.startsWith('--') !== true) continue;
    const name = token.slice(2);
    const value = argv[i + 1];
    if (value === undefined) throw new Error(`--${name} needs a value`);
    args[name] = value;
    i++;
  }
  return args;
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));
  const updateFilePath = args['update-file'];
  if (updateFilePath === undefined) {
    console.error('Usage: apply:research-update -- --update-file <path>');
    process.exitCode = 1;
    return;
  }

  const result = applyResearchUpdateToMigration(updateFilePath);
  if (!result.ok) {
    console.error(`Update refused: ${result.reason}`);
    process.exitCode = 1;
    return;
  }

  console.log('Applied update:');
  for (const [key, count] of Object.entries(result.summary.addedCounts)) {
    console.log(`  ${key}: +${String(count)}`);
  }
  for (const [relationshipId, count] of Object.entries(result.summary.appendedRelationshipStates)) {
    console.log(`  relationship "${relationshipId}": +${String(count)} state(s)`);
  }
  console.log(`\nWrote ${result.migrationPath} (version -> "${result.newVersion}").`);
  console.log(
    '\nOne manual step left — add these two lines to research-store/src/migrations/index.ts:',
  );
  console.log(
    `  import { ${result.exportName} } from './${result.migrationFileName.replace(/\.ts$/, '.js')}';`,
  );
  console.log(`  // ...and add ${result.exportName} to the researchStoreMigrations array.`);
}

const isMainModule =
  process.argv[1] !== undefined && import.meta.url === `file://${process.argv[1]}`;
if (isMainModule) {
  main();
}
