/**
 * Streamlined day-to-day price ingestion: renders a NEW, auto-numbered migration file that grows
 * an ALREADY-published dataset with new daily bars read from a JSON file, instead of writing
 * directly into a local sqlite file (see `docs/adr/0014-sqlite-standard-and-migrations.md`) or
 * hand-writing a bespoke `seed*.ts`/literal-array script per update. Thin wrapper over
 * `renderAppendBarsSql` (`../src/store/sqlGen.ts`) — see that file's own doc comment for the exact
 * "only ever extends the frontier forward, never backfills" semantics this inherits unchanged.
 * Validates against a FRESH replay of this package's own current migrations (never a real file),
 * since the migration history is what "already published" means now.
 *
 * Input file shape — one object, keyed by ticker, each a `DailyBar[]`:
 *   { "KMT": [{ "date": "2026-09-01", "open": 1, "high": 1, "low": 1, "close": 1, "volume": 1 }] }
 * (exactly the per-ticker "Daily prices" block `price-data-request-skill.md` asks for, reshaped
 * from its plain-text table into JSON — see that file for the sourcing discipline new bars must
 * satisfy before they end up here.)
 *
 * Usage:
 *   yarn workspace @thunderdome/market-data run append:bars -- \
 *     --dataset-id fusion-fundamental-v0 --dataset-version 3 --bars-file /path/to/bars.json
 *
 * The generated migration file still needs ONE manual step: add its import + array entry to
 * `market-data/src/migrations/index.ts` (this script prints the exact lines).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { nextMigrationNumber, renderMigrationFileSource } from '@thunderdome/sqlite-migrations';
import { z } from 'zod';
import { createMarketDataStore } from '../src/store/db.js';
import { DailyBarSchema } from '../src/schema/dailyBar.js';
import { renderAppendBarsSql } from '../src/store/sqlGen.js';

const BarsFileSchema = z.record(z.string(), z.array(DailyBarSchema));

const __dirname = dirname(fileURLToPath(import.meta.url));
const MIGRATIONS_DIR = resolve(__dirname, '../src/migrations');

function parseArgs(argv: string[]): Record<string, string> {
  const args: Record<string, string> = {};
  for (let i = 0; i < argv.length; i++) {
    const token = argv[i];
    if (token?.startsWith('--') !== true) continue;
    const name = token.slice(2);
    const value = argv[i + 1];
    if (value === undefined) throw new Error(`--${name} needs a value`);
    args[name] = value;
    i++;
  }
  return args;
}

function main(): void {
  const args = parseArgs(process.argv.slice(2));
  const datasetId = args['dataset-id'];
  const datasetVersion = args['dataset-version'];
  const barsFile = args['bars-file'];
  if (datasetId === undefined || datasetVersion === undefined || barsFile === undefined) {
    console.error(
      'Usage: append:bars -- --dataset-id <id> --dataset-version <version> --bars-file <path>',
    );
    process.exitCode = 1;
    return;
  }

  const raw: unknown = JSON.parse(readFileSync(resolve(barsFile), 'utf8'));
  const parsed = BarsFileSchema.safeParse(raw);
  if (!parsed.success) {
    console.error(
      `"${barsFile}" is not a valid { TICKER: DailyBar[] } map: ${parsed.error.message}`,
    );
    process.exitCode = 1;
    return;
  }

  const store = createMarketDataStore(':memory:');
  const rendered = renderAppendBarsSql(
    store,
    { id: datasetId, version: datasetVersion },
    { bars: parsed.data },
  );
  if (!rendered.ok) {
    console.error(rendered.reason);
    process.exitCode = 1;
    return;
  }

  const number = nextMigrationNumber(MIGRATIONS_DIR);
  const exportName = `migration${number}AppendBars`;
  const id = `market-data/${number}_append_bars`;
  const migrationPath = join(MIGRATIONS_DIR, `${number}_append_bars.ts`);

  const source = renderMigrationFileSource({
    exportName,
    id,
    sql: rendered.value,
    docComment: `/** New bars appended to dataset "${datasetId}" version "${datasetVersion}", generated by\n * \`scripts/appendBarsFromFile.ts\` from ${JSON.stringify(barsFile)} — never hand-edit this\n * file; a correction is always a NEW migration. */`,
  });
  writeFileSync(migrationPath, source, 'utf8');

  for (const [ticker, bars] of Object.entries(parsed.data)) {
    console.log(
      `${ticker}: appended ${String(bars.length)} bar(s), ${bars[0]?.date} through ${bars.at(-1)?.date}`,
    );
  }
  console.log(`\nWrote ${migrationPath}`);
  console.log(
    '\nOne manual step left — add these two lines to market-data/src/migrations/index.ts:',
  );
  console.log(`  import { ${exportName} } from './${number}_append_bars.js';`);
  console.log(`  // ...and add ${exportName} to the marketDataMigrations array.`);
}

main();
